Development
frankkramer-lab/MIScnn pull request #60
Opened 2020-12-15 16:00 UTC by Deathlymad

This moves the extended data and speficially the spacing matrices to the sample object and uses the sample to write files. As the property of the spacing is object bound. With the cache system it could cause lost data on copy or rename.

2020-12-19 22:04 UTC, Deathlymad commented
es fehlt soweit ich sehe ein default fuer extended data um sample objekte zu erstellen.

2021-01-28 15:03 UTC, muellerdo requested changes
- More documentation on model (group) required.
- More code clean up
- Passing sample objects vs only required data to interface IOs
- load_details() function present in some interfaces, but never called + removed from abstract base class?

2021-02-09 16:28 UTC, Deathlymad commented on miscnn/model/model.py
> +class Model():
This was added to this pull request accidentally. I'll remove it.

2021-02-10 15:29 UTC, Deathlymad commented on miscnn/data_loading/data_io.py
> -        sample.add_details(self.interface.load_details(index))
Examples work.

2021-02-10 16:14 UTC, muellerdo commented
Resampling

2021-03-01 10:04 UTC, merged